project_name: zitadel

release:
  github:
    owner: zitadel
    name: zitadel
  draft: false
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto

before:
  hooks:
    # this file would invalidate go source caches
    - sh -c "rm openapi/statik/statik.go || true"
    - docker build -f build/grpc/Dockerfile -t zitadel-base:local .
      #- docker build -f build/zitadel/Dockerfile . -t zitadel-go-test --target go-codecov -o .artifacts/codecov
    - docker build -f build/zitadel/Dockerfile . -t zitadel-go-base --target go-copy -o .artifacts/grpc/go-client
    - sh -c "cp -r .artifacts/grpc/go-client/* ."
    - docker build -f build/console/Dockerfile . -t zitadel-npm-console --target angular-export -o .artifacts/console
    - sh -c "cp -r .artifacts/console/* internal/api/ui/console/static/"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: -s -w -X github.com/zitadel/zitadel/cmd/build.version={{.Version}} -X github.com/zitadel/zitadel/cmd/build.commit={{.Commit}} -X github.com/zitadel/zitadel/cmd/build.date={{.Date}}

dist: .artifacts/goreleaser

dockers:
  - image_templates:
      - ghcr.io/zitadel/zitadel:{{ .Tag }}-amd64
      - europe-docker.pkg.dev/zitadel-common/zitadel-repo/zitadel:{{ .Tag }}-amd64
    goarch: amd64
    use: buildx
    dockerfile: build/Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - ghcr.io/zitadel/zitadel:{{ .Tag }}-arm64
      - ghcr.io/zitadel/zitadel:{{ .ShortCommit }}-arm64
    goarch: arm64
    use: buildx
    dockerfile: build/Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - id: zitadel-latest
    name_template: ghcr.io/zitadel/zitadel:latest
    image_templates:
      - ghcr.io/zitadel/zitadel:{{ .Tag }}-amd64
      - ghcr.io/zitadel/zitadel:{{ .Tag }}-arm64
    # Skips can and shall be set for individual manifests same as in dockers
    skip_push: auto
  - id: zitadel-Tag
    name_template: ghcr.io/zitadel/zitadel:{{ .Tag }}
    image_templates:
      - ghcr.io/zitadel/zitadel:{{ .Tag }}-amd64
      - ghcr.io/zitadel/zitadel:{{ .Tag }}-arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

gomod:
  proxy: false

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - tap:
      owner: zitadel
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_TOKEN_TAP }}"
    folder: Formula
    goarm: "7"
    homepage: https://zitadel.com
    description: Open source identity solution built for the container and cloud era
    license: Apache 2.0
    test: |
      system "#{bin}/zitadel -v"
    dependencies:
      - name: go
        type: optional
      - name: git
    install: |-
      bin.install "zitadel"
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    skip_upload: auto

announce:
  discord:
    enabled: true
    message_template: "ZITADEL {{ .Tag }} is ready! Check the notes: https://github.com/zitadel/zitadel/releases/tag/{{ .Tag }}"
